### ISSUE TITLE
[enhancement] feature request: being able to build support for specific hardware only

### ISSUE THREAD

**Issue by febs** [f4exb/sdrangel-docker#11]
The docker image and the pre-made scripts such as "build_vanilla.sh" to build sdrangel are very handy. 

Nevertheless, it looks to me it is building support for all hardware in any case. 
I do personally only own an hackrf. Building for RTL-SDR, sdrplay, and the other supported units is a waste of time and of CPU cycles. 
Being able to be selective about which drivers to build would be a nice improvement in my opinion.

Thanks

**Comment by f4exb** [comment]
This is fine as it is actually. The image build uses the Docker "buildkit" option and a staged approach so the cache build is extensively used already. You run the full build only once and once in a while when the Dockerfile changes significantly. Moreover you will not build a new image every day and you can let the computer build the image when you are doing something else.

**Comment by febs** [comment]
I see your point.
Building the first instance can still be overwhelming too, (especially if you are low of network speed, or hard drive space, or computational power), even if you do that only once (or mostly once).
But if you see no point in adding complication to the scripts to deal with this then, fine. It iis an inconvenience, after all, not a but.

Thanks for your work.
