### ISSUE TITLE
 importing from FFTW wisdom file: '/home/sdr/.config/sdrangel/' failed

### ISSUE THREAD

**Issue by febs** [f4exb/sdrangel-docker#12]
Scenario:

- I build sdrangel with ./build_vanilla.sh from the "sdrangel" directory
- I build fftwistom with ./build.sh from within the "fftwisdom" directory
- I run fftwisdom by running ./run.sh from within the "fftwisdom" directory. That creates _~/.config/sdrangel/fftw-wisdom_
- I run ./run.sh -g from within "sdrangel" to launch the sdrangel GUI and in the logs I get:

>  importing from FFTW wisdom file: '/home/sdr/.config/sdrangel/' failed

...a few times.

Did I miss something? According to the documentation that should be the default path if I don't specify any with "-w", is that wrong?

**Comment by f4exb** [comment]
There is a problem here actually: https://github.com/f4exb/sdrangel-docker/blob/master/sdrangel/run.sh#L78

It should be:
```shell
--env FFTWFILE=${fftw_filename} \
```

**Comment by febs** [comment]
That solved the issue, thank you.
