### ISSUE TITLE
Can't run wsjtx

### ISSUE THREAD

**Issue by febs** [f4exb/sdrangel-docker#13]
in the "wsjtx" directory.

./build.sh can build the image nicely
./run.sh gives

> 
> laptop sdrangel-docker/wsjtx ‹master› » ./run.sh 
> Unable to find image 'wsjtx/bionic:latest' locally
> docker: Error response from daemon: pull access denied for wsjtx/bionic, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.

I have no other permissions issue in my docker installation (i.e, dockerized sdrangel runs fine without ever using root).

Docker version 19.03.9, build 9d988398e7

Thanks,

**Comment by f4exb** [comment]
The `wsjtx/bionic:latest` image is not available from any public repository. You have to build it yourself. The message from Docker is pretty explicit. Use the `build.sh` script in the `wsjtx` directory. See: https://github.com/f4exb/sdrangel-docker/tree/master/wsjtx#build-image

**Comment by febs** [comment]
Thanks for your reply. That is what I done, as I described in the first post.

I ran the `build.sh `script in the `wsjtx` directory, but then runing `./run.sh` in the very same direcrory files with that message.

**Comment by f4exb** [comment]
OK I think I understand your scenario. 
  - `build.sh` tags the image with the WSJTX version which is `v2.1.2` so the resulting image is `wsjtx/bionic:v2.1.2` you can check it with `docker images` command
  - `run.sh` runs the image with the `latest` tag as default so it expects `wsjtx/bionic:latest`. Then you have two options:
    - tag the `v2.1.2` image as `latest`: `docker tag wsjtx/bionic:v2.1.2 wsjtx/bionic:latest`
    - run with the `v2.1.2` tag specified: `run.sh -t v2.1.2`

**Comment by febs** [comment]
That did the trick, thanks. 
But shouldn't _latest_ just point to the most recet tag, that is 2.1.2 in this case?
