### ISSUE TITLE
Can't build sdrangel v5

### ISSUE THREAD

**Issue by febs** [f4exb/sdrangel-docker#15]
according to the documentation (readme file in "sdrangel folder"),  `-b` specifies which branch you are checking out in the clone (default is `master`). 

so I execute ./build.sh -b v5  
and the command ends with
 _naming to docker.io/sdrangel/vanilla:latest_ 

the incipit of the "run.sh" file says Usage: ${0##*/} [-g] **[-b branch]**
Unfortunately
./run.sh -g -b v5

gives this output
```
./run.sh: 1: /home/fabio/.config/sdrangel: Permission denied
  Usage: run.sh [-g] [-b branch] -t version [-k name] [-s port] [-a port] [-u port [-u port ...]] [-h]
  Run SDRangel in a Docker container.
  -g         Run a GUI variant (server if unset)
  -f         Image flavor. Can be vanilla, nvidia, server16, server24 (default vanilla). Use a flavor relevant to GUI or server variants.
  -t tag     Docker image tag version (default latest). Use the corresponding image tag.
  -c name    Docker container name (default sdrangel)
  -s port    SSH port map to 22.
  -a port    API port map to 8091 (default 8091).
  -u port    UDP port map to same with UDP option. Can be repeated.
  -w name    FFTW wisdom file name in the  directory (default fftw-wisdom).
  -h         Print this help.
  Examples:
    ./run.sh -g -c sdrangel -s 50022 -u 9090:9090 (starts sdrangel/vanilla:latest)
    ./run.sh -g -f nvidia -t v4.10.4 -c sdrangel -s 50022 -u 9090:9090 (starts sdrangel/nvidia:v4.10.4)
    ./run.sh -f server16 -t 38df0a6 -c sdrangel -s 50022 -u 9090:9090 (starts sdrangel/server16:38df0a6)

```

Docker version 19.03.9, build 9d988398e7

thanks

**Comment by f4exb** [comment]
You have to understand how Docker works and understand the scripts a bit more. It does not make sense to specify the branch on the run step thus the `-b` option is simply not there. The help of the command is correct and the readme is wrong. It used to be like that but that was changed some time ago. What matters at his point is the Docker image not from which branch of sdrangel it was built. There is an image name and a tag (from Docker not git) period. The scripts make no assumptions on how you manage your images.

To keep things tidy `./build.sh -b v5` is clearly not enough. At this moment the tip of `v5` branch has the `v5.6.2` tag so it would make sense to tag the image as `v5.6.2` with: `./build.sh -b v5 -t v5.2.6`. This results in the `sdrangel/vanilla:v5.6.2` image. To make things more convenient the next step is to tag this version as latest: `docker tag sdrangel/vanilla:v5.6.2 sdrangel/vanilla:latest`. When you build a new image for say `v5.6.3` later then you just move the `latest` tag by applying the `docker tag` command again with the new image. If the tip of `v5` is not tagged just use the short SHA commit thus you know with which version of sdrangel this image was built. 

Then if you run just `./run.sh` it will look for `sdrangel/vanilla:latest` image. By the way this is not `docker.io/sdrangel/vanilla:latest`. I don't know how it ended up with this name. There must be something fishy in your Docker configuration.

**Comment by febs** [comment]
Thanks, I was actually able to run it with the vanilla:latest image name. 

What I wanted to report was the inconsistency between the documentation and the behavior.

**Comment by febs** [comment]
Closed by accident being the inaccurate naming/description is still there.
