### ISSUE TITLE
docker 19.03.x and building the docker images

### ISSUE THREAD

**Issue by roelandjansen** [f4exb/sdrangel-docker#2]
in july it worked fine; now it doesn't. Maybe a bug somewhere in docker itself:

Docker version 19.03.1, build 74b1e89e8ac6

sdrangel build_vanilla:

 => ERROR [base 21/23] COPY pulse-client.conf /etc/pulse/client.conf                                                                                  0.3s
------
 > [base 21/23] COPY pulse-client.conf /etc/pulse/client.conf:
------
no such file or directory

and the sdrangelcli:

 => [base 6/7] RUN sudo mkdir /opt/build      && sudo chown node:node /opt/build                                                                      0.7s
 => ERROR [base 7/7] WORKDIR /opt/build                                                                                                               0.7s
------
 > [base 7/7] WORKDIR /opt/build:
------
no such file or directory

the latter happens on sdrangel too if I comment out the first COPY command where it fails.

any ideas?

**Comment by f4exb** [comment]
Is the log complete? These errors do not make sense unless something unexpected has happened before.

**Comment by roelandjansen** [comment]
I snipped the console log as it all went fine.

This is the console log. 

roeland@taplop:~/src/sdrangel-docker/sdrangel> ./build_vanilla.sh 
[+] Building 420.9s (25/97)                                                                                                                                                                     
 => [internal] load .dockerignore                                                                                                                                                          0.6s
 => => transferring context: 103B                                                                                                                                                          0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                       0.5s
 => => transferring dockerfile: 18.07kB                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:18.04                                                                                                                            1.7s
 => [internal] load build context                                                                                                                                                          0.3s
 => => transferring context: 980B                                                                                                                                                          0.0s
 => [base 1/23] FROM docker.io/library/ubuntu:18.04@sha256:b88f8848e9a1a4e4558ba7cfc4acc5879e1d0e7ac06401409062ad2627e6fb58                                                                5.3s
 => => resolve docker.io/library/ubuntu:18.04@sha256:b88f8848e9a1a4e4558ba7cfc4acc5879e1d0e7ac06401409062ad2627e6fb58                                                                      0.0s
 => => sha256:5667fdb72017d1fb364744ca1abf7b6f3bbe9c98c3786f294a461c2866db69ab 26.68MB / 26.68MB                                                                                           1.6s
 => => sha256:d83811f270d56d34a208f721f3dbf1b9242d1900ad8981fc7071339681998a31 35.35kB / 35.35kB                                                                                           0.2s
 => => sha256:ee671aafb583e2321880e275c94d49a49185006730e871435cd851f42d2a775d 850B / 850B                                                                                                 0.1s
 => => sha256:b88f8848e9a1a4e4558ba7cfc4acc5879e1d0e7ac06401409062ad2627e6fb58 1.42kB / 1.42kB                                                                                             0.0s
 => => sha256:1bbdea4846231d91cce6c7ff3907d26fca444fd6b7e3c282b90c7fe4251f9f86 1.15kB / 1.15kB                                                                                             0.0s
 => => sha256:2ca708c1c9ccc509b070f226d6e4712604e0c48b55d7d8f5adc9be4a4d36029a 3.41kB / 3.41kB                                                                                             0.0s
 => => sha256:7fc152dfb3a6b5c9a436b49ff6cd72ed7eb5f1fd349128b50ee04c3c5c2355fb 163B / 163B                                                                                                 0.4s
 => => extracting sha256:5667fdb72017d1fb364744ca1abf7b6f3bbe9c98c3786f294a461c2866db69ab                                                                                                  1.0s
 => => extracting sha256:d83811f270d56d34a208f721f3dbf1b9242d1900ad8981fc7071339681998a31                                                                                                  0.0s
 => => extracting sha256:ee671aafb583e2321880e275c94d49a49185006730e871435cd851f42d2a775d                                                                                                  0.0s
 => => extracting sha256:7fc152dfb3a6b5c9a436b49ff6cd72ed7eb5f1fd349128b50ee04c3c5c2355fb                                                                                                  0.0s
 => [base 2/23] RUN apt-get update && apt-get -y install sudo                                                                                                                              9.8s
 => [base 3/23] RUN useradd -m sdr -u 1000 && echo "sdr:sdr" | chpasswd    && adduser sdr sudo    && usermod -a -G audio,dialout,plugdev sdr   && sudo usermod --shell /bin/bash sdr       1.1s
 => [base 4/23] RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers                                                                                                                    0.9s 
 => [base 5/23] RUN sudo ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime     && sudo apt-get update && sudo apt-get -y install tzdata                                               5.7s 
 => [base 6/23] RUN sudo apt-get update && sudo apt-get -y install   vim   openssh-server   iputils-ping   traceroute   iproute2   nmap     net-tools     python-requests     python-fla  74.4s 
 => [base 7/23] RUN sudo apt-get update && sudo apt-get -y install     git     cmake     g++     pkg-config     autoconf     automake     libtool     libfftw3-dev     libusb-1.0-0-dev   45.4s 
 => [base 8/23] RUN sudo apt-get update && sudo apt-get -y install     qtbase5-dev     qt5-default                                                                                        51.6s 
 => [base 9/23] RUN sudo apt-get update && sudo apt-get -y install     qtchooser     libqt5multimedia5-plugins     qtmultimedia5-dev     libqt5websockets5-dev                            15.3s 
 => [base 10/23] RUN sudo apt-get update && sudo apt-get -y install     qttools5-dev     qttools5-dev-tools                                                                               23.8s 
 => [base 11/23] RUN sudo apt-get update && sudo apt-get -y install     libqt5opengl5-dev                                                                                                  4.9s 
 => [base 12/23] RUN sudo apt-get update && sudo apt-get -y install     libpython2.7 libpython2.7-dev                                                                                     10.7s 
 => [base 13/23] RUN sudo apt-get update && sudo apt-get -y install     libpython3-dev                                                                                                    20.1s 
 => [base 14/23] RUN sudo apt-get update && sudo apt-get -y install     libpython3.6-dev                                                                                                   4.9s 
 => [base 15/23] RUN sudo apt-get update && sudo apt-get -y install     librdmacm1                                                                                                         6.1s 
 => [base 16/23] RUN sudo apt-get update && sudo apt-get -y install     libboost-all-dev                                                                                                  34.9s 
 => [base 17/23] RUN sudo apt-get update && sudo apt-get -y install     libasound2-dev     pulseaudio     libopencv-dev     libxml2-dev     bison     flex     ffmpeg     libavcodec-dev  83.7s 
 => [base 18/23] RUN sudo apt-get update && sudo apt-get -y install libspeexdsp-dev     libsamplerate0-dev                                                                                 6.2s 
 => [base 19/23] RUN sudo apt-get update && sudo apt-get -y install xxd                                                                                                                    4.9s 
 => [base 20/23] RUN sudo apt-get update && sudo apt-get -y install python-cheetah     python-mako                                                                                         8.0s 
 => ERROR [base 21/23] COPY pulse-client.conf /etc/pulse/client.conf                                                                                                                       0.4s 
------                                                                                                                                                                                          
 > [base 21/23] COPY pulse-client.conf /etc/pulse/client.conf:                                                                                                                                  
------                                                                                                                                                                                          
no such file or directory      


I'll see if there is more logging

**Comment by roelandjansen** [comment]
if I move the copy statement down to build_dep it will directly trip over the next line:

WORKDIR /opt/build


e.g the part :

# Prepare buiid and install environment
RUN sudo mkdir /opt/build /opt/install \
    && sudo chown sdr:sdr /opt/build /opt/install

WORKDIR /opt/build


line with the same error as stated in the first post.

**Comment by roelandjansen** [comment]
it definitely is a race condition:

[....]
=> [base 20/23] RUN sudo apt-get update && sudo apt-get -y install python-cheetah     python-mako                                                                                                                                                                 8.9s
=> [base 21/23] COPY pulse-client.conf /etc/pulse/client.conf                                                                                                                                                                                                     0.1s
=> [base 22/23] RUN sudo mkdir /opt/build /opt/install     && sudo chown sdr:sdr /opt/build /opt/install                                                                                                                                                          0.7s
=> [base 23/23] WORKDIR /opt/build
[...]

the build failure happens when I switch from ssd to spinning rust (NAS)

**Comment by f4exb** [comment]
What I meant is that you need to move this COPY statement completely out of the "base" section i.e. somewhere after something that starts with "FROM base AS blahblah". In fact it can be done anytime even very late but a convenient place where things are still in common is the "base_deps" section so I would move it there. That is right after https://github.com/f4exb/sdrangel-docker/blob/master/sdrangel/Dockerfile#L390

I haven't had time to try this myself but this is something to be fixed eventually btw this is the only COPY statement in the "base" section and it should not be there because at that point the base environment is effectively not built yet. It may work by chance only.

**Comment by roelandjansen** [comment]
if I move it completely down, out of the base section, or completely remove it -- it then will fail on WORKDIR /opt/build with the same error as mentioned in the first post.

If I swap out the gbit connected NAS to local ssd storage, it builds fine; both sdrangel as well as the cli; if I go back to the NAS/spinning rust, it fails. every time.

So for me it is a race condition.

**Comment by f4exb** [comment]
With the latest Docker files committed to master I have been able to build flawlessly on my laptop (x86-64) and also on Rock64 and RPi4 (armv8). This is with Docker 19.03.4 that has fixed the overlayfs bug.

**Comment by roelandjansen** [comment]
I have 19.03.1  (will have to wait until 19.03.4 is available)

I merged your changes and it still is catched by a race condition:
And as noted: It happens when the storage is remote via 1Gbit.
Local ssd storage works fine so far.
[....]
------
 > [sdrangel_clone 1/2] WORKDIR /opt/build:
------
no such file or directory


So I'll wait until 19.03.4 is available.

**Comment by f4exb** [comment]
Remote storage can be an issue in general as I am not sure Docker default overlayfs supports it. All my builds are based on overlayfs2 over ext4.
