### ISSUE TITLE
Can't build with "build_linux_nvidia.sh"

### ISSUE THREAD

**Issue by febs** [f4exb/sdrangel-docker#23]
foreword: I identified the Nvidia driver version string as indicated by the [readme file](https://github.com/f4exb/sdrangel-docker/blob/master/sdrangel/readme.md) and was about to download it manually as instructed. 
I ran "build_linux_nvidia.sh" beforehand though, out of curiosity, and saw that the script wgets it and renames it on its own. I checked by executing that binary manually and was of course the right one indeed.

That being said, the "build_linux_nvidia.sh" script, here, ends up with 

>  ERROR [linux_nvidia 3/7] RUN sudo sh /tmp/NVIDIA-DRIVER.run -s --ui=none --no-kernel-module --install-libglvnd --no-questions                11.7s
>  > [linux_nvidia 3/7] RUN sudo sh /tmp/NVIDIA-DRIVER.run -s --ui=none --no-kernel-module --install-libglvnd --no-questions:
> #96 0.938 Verifying archive integrity... OK
> #96 1.618 Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 340.108...................................................................................................................................................................................................................................
> #96 10.55 **./nvidia-installer: unrecognized option: "--install-libglvnd"**
> #96 10.55 
> #96 10.55 ERROR: Invalid commandline, please run `./nvidia-installer --help` for
> #96 10.55        usage information.
> #96 10.55 
> ------

Nvidia version 340.108.

Thank you,

**Comment by f4exb** [comment]
Problem with NVIDIA driver compile. version 340.108 is quite old. Never tried with a driver older than 390. Currently 440.

**Comment by f4exb** [comment]
Answer is here: https://bbs.archlinux.org/viewtopic.php?id=242625: "nvidia-340xx-libgl is only for legacy nvidia cards where the driver doesn't implement libglvnd"

In general libgvlnd is necessary for up to date drivers and graphic cards so sorry no support for legacy cards and 340 driver.

I think this closes the issue.

**Comment by febs** [comment]
I removed "--install-libglvnd" from the Dockerfile and was able to build the image, if that might be of intereset. I was _not_ able to run it because it complained it could not connect to the X server but I guess that's another issue.
