### ISSUE TITLE
Issue creating SDRangel-docker

### ISSUE THREAD

**Issue by f5vat** [f4exb/sdrangel-docker#3]
Hi,

Trying to create SDRangel docker container per directions. cm256cc causes failure - trying to compile cm256cc manually gives same error "Unsupported architecture - Terminated".

Any ideas?
Nick F5VAT

 > [cm256cc 2/2] RUN git clone https://github.com/f4exb/cm256cc.git     && cd cm256cc     && git reset --hard f21e8bc1e9afdb0b28672743dcec111aec1d32d9     && mkdir build; cd build     && cmake -Wno-dev -DCMAKE_INSTALL_PREFIX=/opt/install/cm256cc ..     && make -j2 install:
#26 19.04 Cloning into 'cm256cc'...
#26 44.70 HEAD is now at f21e8bc cmake SIMD test programs: avoid possible core dumps by catching SIGILL
#26 45.88 -- The C compiler identification is GNU 7.4.0
#26 46.83 -- The CXX compiler identification is GNU 7.4.0
#26 46.88 -- Check for working C compiler: /usr/bin/cc
#26 47.91 -- Check for working C compiler: /usr/bin/cc -- works
#26 47.92 -- Detecting C compiler ABI info
#26 49.24 -- Detecting C compiler ABI info - done
#26 49.32 -- Detecting C compile features
#26 52.99 -- Detecting C compile features - done
#26 53.04 -- Check for working CXX compiler: /usr/bin/c++
#26 54.59 -- Check for working CXX compiler: /usr/bin/c++ -- works
#26 54.60 -- Detecting CXX compiler ABI info
#26 56.30 -- Detecting CXX compiler ABI info - done
#26 56.43 -- Detecting CXX compile features
#26 67.44 -- Detecting CXX compile features - done
#26 69.32 -- Target architecture: x86_64
#26 72.16 -- Use SSE2 SIMD instructions
#26 104.5 -- Unsupported architecture - Terminated
#26 104.5 -- Configuring done
#26 104.6 -- Generating done
#26 104.9 -- Build files have been written to: /opt/build/cm256cc/build
#26 108.7 make: *** No rule to make target 'install'.  Stop.

**Comment by f4exb** [comment]
This is simple: the architecture on which you build the image is not supported.

**Comment by f5vat** [comment]
OK thanks. Yes. Seems my AMD Athlon 64 X2 does not support SSE3. Some revisions do other don't. Mine doesn't. Time to upgrade!
73 de Nick F5VAT
