### ISSUE TITLE
Issue with SoapySDRPlay: Remove SoapySDR SDRPlay support

### ISSUE THREAD

**Issue by mantis4** [f4exb/sdrangel-docker#30]
Hello. 
I'm trying build a image using `build_vanilla.sh ` and I get error:
![image](https://user-images.githubusercontent.com/31863810/104105976-3a96e500-52c3-11eb-99b6-b79c413cb178.png)

How to fix it?

**Comment by f4exb** [comment]
This is due to mess up in SoapySDRPlay repository. It turns out that this repository has been reworked and the tag has disappeared. Moreover one cannot access SoapySDRPlay repository which redirects to SoapySDRPlay3. I think it is time to get rid of this mess and remove SoapySDR SDRPlay altogether.
