### ISSUE TITLE
NVIDIA driver download step

### ISSUE THREAD

**Issue by gigawatts** [f4exb/sdrangel-docker#32]
I'm a bit confused about the NVIDIA driver download pre-requirement. 

If you follow the instructions in the readme, and manually download / copy the version of the NVIDIA driver you are currently using on your system into the /sdrangel/ dir and rename it to `NVIDIA-DRIVER.run`, then run `./build_linux_nvidia.sh`, it downloads the same exact file again anyway.

However, if you don't pre-download / copy / rename the driver run file, it fails saying the `NVIDIA-DRIVER.run`  does not exist.

Why require that file pre-exist, if the script is just going to go wget the same exact file again anyway, based on what your system has installed?

Maybe it would be better to instead warn the user if the system can't detect what version is currently installed (from glxinfo), and if it can detect what version is installed AND the driver file does not preexist, to THEN go ahead and wget it.

**Comment by f4exb** [comment]
The instructions have not been updated when the automatic download process was put in place. 

However this process could be changed to rely on the presence of `NVIDIA-DRIVER.run` and attempt an initial download or an upgrade only if it is not present. Thus the user may use any version of the driver to build an image for another system for example or let the script find and download the driver that matches the host system if `NVIDIA-DRIVER.run`. 

When a driver upgrade takes place one just deletes this file before re-building the image.
