### ISSUE TITLE
build_vanilla.sh chews up massive disk space

### ISSUE THREAD

**Issue by tranzmatt** [f4exb/sdrangel-docker#4]
I'm trying to build the "vanilla" image via the build_vanilla.sh, but it seems to only get so far before it starts gobbling up massive amounts of disk space.  I have 260+GB on the / and it'll eat every one and if I kill it an system prune, it'll say it freed 630GB(!).  I don't know if it really wanted that much or what, but has anyone run into something similar?

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.04
Release:	19.04
Codename:	disco

Docker version 19.03.3, build a872fc2f86

**Comment by f4exb** [comment]
No issues here with Docker 19.03.5 either in x86_64 or ARM64 (Raspberry Pi4). Both on Ubuntu 18.04

**Comment by tranzmatt** [comment]
It must be 19.04, then.  I was able to build on 19.10 on another x64 box
