### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Klammraute** [f4exb/sdrangel-docker#52]
I use a raspberry PI4 as server when i try to run "./build_server.sh -f armv8.ubuntu.Dockerfile" on ubuntu server 22
i get the following error.
How to solve this error? 

=> ERROR [base  3/17] RUN useradd -m sdr -u 0 && echo "sdr:sdr" | chpasswd    && adduser sdr sudo    && usermod -a -G audio,dial  2.0s
------
 > [base  3/17] RUN useradd -m sdr -u 0 && echo "sdr:sdr" | chpasswd    && adduser sdr sudo    && usermod -a -G audio,dialout,plugdev sdr   && sudo usermod --shell /bin/bash sdr:
0.765 useradd: UID 0 is not unique
------
armv8.ubuntu.Dockerfile:8
--------------------
   7 |     RUN apt-get update && apt-get -y install sudo
   8 | >>> RUN useradd -m sdr -u ${uid} && echo "sdr:sdr" | chpasswd \
   9 | >>>    && adduser sdr sudo \
  10 | >>>    && usermod -a -G audio,dialout,plugdev sdr\
  11 | >>>    && sudo usermod --shell /bin/bash sdr
  12 |     RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
--------------------
ERROR: failed to solve: process "/bin/sh -c useradd -m sdr -u ${uid} && echo \"sdr:sdr\" | chpasswd    && adduser sdr sudo    && usermod -a -G audio,dialout,plugdev sdr   && sudo usermod --shell /bin/bash sdr" did not complete successfully: exit code: 4

thanks

**Comment by f4exb** [comment]
you should not build the image from the root user account

**Comment by f4exb** [comment]
Fixed in commit 6caaf12 as Ubuntu 24.04 armv8 image already has user 1000. So the corresponding Dockerfile was updated to circumvent the issue.
